In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("nvd_training_data.csv")

In [4]:
df.head()

,cve,cvss_score,severity,severity_num,port,service,is_public,has_exploit,in_cisa_kev,in_exploitdb,attackVector,attackComplexity,privilegesRequired,userInteraction,gold_risk_score,source
0,CVE-1999-0426,9.8,CRITICAL,4,0,unknown,0,1,0,1,NETWORK,LOW,NONE,NONE,10.0,NVD+ExploitDB
1,CVE-1999-1324,9.8,CRITICAL,4,0,unknown,0,1,0,0,NETWORK,LOW,NONE,NONE,10.0,NVD
2,CVE-2000-1218,9.8,CRITICAL,4,0,unknown,0,1,0,0,NETWORK,LOW,NONE,NONE,10.0,NVD
3,CVE-2000-0944,9.8,CRITICAL,4,0,unknown,0,1,0,1,NETWORK,LOW,NONE,NONE,10.0,NVD+ExploitDB
4,CVE-2001-1339,9.8,CRITICAL,4,0,unknown,0,1,0,1,NETWORK,LOW,NONE,NONE,10.0,NVD+ExploitDB

In [5]:
df.isna().sum()

cve                   0
cvss_score            0
severity              0
severity_num          0
port                  0
service               0
is_public             0
has_exploit           0
in_cisa_kev           0
in_exploitdb          0
attackVector          0
attackComplexity      0
privilegesRequired    0
userInteraction       0
gold_risk_score       0
source                0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41118 entries, 0 to 41117
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cve                 41118 non-null  object
 1   cvss_score          41118 non-null  float64
 2   severity            41118 non-null  object
 3   severity_num        41118 non-null  int64
 4   port                41118 non-null  int64
 5   service             41118 non-null  object
 6   is_public           41118 non-null  int64
 7   has_exploit         41118 non-null  int64
 8   in_cisa_kev         41118 non-null  int64
 9   in_exploitdb        41118 non-null  int64
 10  attackVector        41118 non-null  object
 11  attackComplexity    41118 non-null  object
 12  privilegesRequired  41118 non-null  object
 13  userInteraction     41118 non-null  object
 14  gold_risk_score     41118 non-null  float64
 15  source              41118 non-null  object
dtypes: float64(2), int64(6), object(8)
memory usage: 5.0+ MB

In [10]:
df.describe()

,cvss_score,severity_num,port,is_public,has_exploit,in_cisa_kev,in_exploitdb,gold_risk_score
count,41118.000000,41118.000000,41118.000000,41118.000000,41118.000000,41118.000000,41118.000000,41118.000000
mean,7.413972,2.836373,201.714310,0.029671,0.343864,0.018702,0.075903,7.572163
std,2.057706,0.934787,853.580216,0.169679,0.475002,0.135473,0.264847,2.146788
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.900000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.100000
50%,7.500000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.800000
75%,9.800000,4.000000,0.000000,0.000000,1.000000,0.000000,0.000000,10.000000
max,10.000000,4.000000,27017.000000,1.000000,1.000000,1.000000,1.000000,10.000000

In [17]:
df.select_dtypes(include="object").columns

Index(['cve', 'severity', 'service', 'attackVector', 'attackComplexity',
       'privilegesRequired', 'userInteraction', 'source'],
      dtype='object')

In [15]:
df["severity"].value_counts()

severity
MEDIUM      13023
HIGH        12946
CRITICAL    12198
LOW          2950
NONE            1
Name: count, dtype: int64

# Legendes des severités
CRITICAL = 4
MEDIUM= 3
LOW = 2
None = 1

# legendes pour attackerVector
Network = 1
Local = 0

# legendes privilegeRequired
High = 4
Medium = 3
Low = 2
None = 1

# legendes interackrequiered
REQUIRED=1
None = 0